### PR TITLE
depend on project not aar

### LINKED ISSUE #29: Latest Gradle does not support projectless .AARs, project changes are needed.
The Android project recommends setting up a projectless aar in: `./app/src/main/libs/PushIOManager.aar`. This is incompatible with latest Gradle, which does not accept projectless .aars and will throw compile time errors when you try to assemble an APK with this aar:
```
* What went wrong:
Execution failed for task ':react-native-pushiomanager:bundleDebugAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :react-native-pushiomanager project caused this error: /Users/admin/Documents/Development/shipt/nebula/android/app/src/main/libs/PushIOManager-6.48.1.aar
```

Instead, the .aar needs to be placed in a standalone directory with a build.gradle file. For example:
```
.
android/PushIOManager/build.gradle
android/PushIOManager/PushIOManager-6.48.1.aar
```

This can then be setup as a project within the user's settings.gradle:
```
include ':PushIOManager'
project(':PushIOManager').projectDir = new File(rootProject.projectDir, './PushIOManager)
```

Your react native project can then depend on a `:PushIOManager` project existing at `./PushIOManager` and declared in that user's settings.gradle. The build.gradle of the react-native-pushiomanager should depend on the ":PushIOManager" project rather than the AAR. 

Inside of react-native-pushiomanager replace:

`implementation rootProject.files('app/src/main/libs/PushIOManager-6.48.1.aar')` 

with: 

 `implementation project(":PushIOManager")` or similar.

### PR DESCRIPTION
**Pull request by shamilovtim**
**Breaking changes**

- Fixes Gradle compilation by depending on the user setting up a project rather than an AAR
- Fixes #29

### CODE REVIEW

**Comment by shamilovtim** [comment]
any ETA on this @neerhaj

**Comment by diegotsi** [comment]
we really need this.

**Comment by Gustavo-Kuze** [comment]
Hello @neerhaj 

Is this fixed in the latest 6.50.1 version? I'm getting this error when I execute `gradlew assembleRelease`:

```
> Task :oracle_react-native-pushiomanager:bundleReleaseAar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':oracle_react-native-pushiomanager:bundleReleaseAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :oracle_react-native-pushiomanager project caused this error: C:\git\concept-bank\android\app\src\main\libs\PushIOManager-6.50.aar
```

**Comment by shamilovtim** [comment]
it's not in 6.50.1 you'll have to install the repo or they'll have to publish a patch

**Pull request merged**
